version: "3.8"
name:   'spring-boot-microservice-bookshop-app'
services:
  catalog-service:
    image: paketobuildpacks/bookshop-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:15432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8085/catalog
      - MANAGEMENT_TRACKING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACKING_ENDPOINT=http://tempo9090
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  order-service:
    image: paketobuildpacks/bookshop-order-service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://orders-db:25432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=bookshop-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - OAUTH2_SERVER_URL=http://keyloak:9111
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8085/orders
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9090
    ports:
      - "8084:8084"
    restart: unless-stopped
    depends_on:
      orders-db:
        condition: service_healthy
      bookshop-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  notification-service:
    image: paketobuildpacks/bookshop-order-service
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://notifications-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=bookshop-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MANAGEMENT_TRACING_ENABLED=true
      - OAUTH2_SERVER_URL=http://keyloak:9111
    ports:
      - "8088:8088"
    restart: unless-stopped
    depends_on:
      notifications -db:
        condition: service_healthy
      bookshop-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  api-gateway:
    image: paketobuildpacks/bookshop-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CATALOG_SERVICE_URL=http://catalog-service:8081
      - ORDER_SERVICE_URL=http://order-service:8084
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http:tempo:9090
    ports:
      - "8989:8989"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  bookshop-webapp:
    image: paketobuildpacks/bookshop-webapp
    container_name: bookshop-webapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BOOKSTORE_API_GATEWAY_URL=http:/api-gateway:8085
      - OAUTH2_SERVE_URL=http://keycloak:9111
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9090
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"


